[theme]
primaryColor = "#f63366"
# backgroundColor = "#10344b"
backgroundColor = "#201919ff"
# secondaryBackgroundColor = "#154360"
secondaryBackgroundColor = "#393939"
textColor = "#fafafa"
font = "sans serif"

[server]
enableStaticServing = true